= Cgit and go modules
2021-05-19
:tags: cgit, go, public, en

Recently I started to self host my public git repositories on git.ewintr.nl. _note: I later moved them to codeberg.org[https://codeberg.org/ewintr]_ There are several options to choose from if you want that sort of thing, like https://gitea.com[Gitea] or https://gogs.io[Gogs] and others. These all look like fine applications, but they all try to imitate the big hosted platforms like Github and GitLab. They do more that making your repositories available to the web, they also include issue trackers, users, project management, etc. That's a bit too much for me. I only want to offer the code of my personal projects that I write about, nothing more.

Fortunately I found https://git.zx2c4.com/cgit/about/[cgit]. Cgit does just that. No collaboration features, but it does its job in a fast, simple and clean way. If its good enough for the https://git.kernel.org/pub/scm/[Linux kernel], it's good enough for me. https://blog.stefan-koch.name/2020/02/16/installing-cgit-nginx-on-debian[This blogpost] covers how to set it up on Debian.

If you use this for hosting Go projects, there is however an extra step you should take. The location for remote Go modules are indicated by import strings at the top of your code and in your `go.mod` file that indicate an url. But a string alone is not enough to make everything work smoothly in the background, if you for instance use `go get`, or `go mod tidy`. There are different types of version control systems, different protocols to transport the data, like `http(s)` and `ssh`. Did you know that git even has its own protocol for serving repositories? (See https://git-scm.com/book/en/v2/Git-on-the-Server-Git-Daemon[git-dameon] for that. It's even lighter than cgit, but insecure, so `go get` doesn't want to download over it without extra confirmation, which is a hassle.)

The extra ingredient necessary for making `go get` work with a remote repository is an extra `<meta>` tag in the header of the repository's website. See the documentation https://golang.org/cmd/go/#hdr-Remote_import_paths[here] for the details.

Luckily, https://mygit.katolaz.net/katolaz/cgit-70/commit/b522a302c9c4fb9fd9e1ea829ee990afc74980ca[someone already modified] `cgit` with an option to provide this tag: `extra-head-content`. We can pass the necessary `<meta>` tag unmodified through this setting. For instance, this is the configuration of one of the repositories on my instance:

----
repo.url=go-kit
repo.owner=Erik Winter
repo.path=/var/repo/public/go-kit/
repo.desc=a small, personal collection of useful go packages
repo.extra-head-content=<meta name="go-import" content="git.ewintr.nl/go-kit git https://git.ewintr.nl/go-kit">
----

== Sources

* https://git.zx2c4.com/cgit/about/[https://git.zx2c4.com/cgit/about/]
* https://blog.stefan-koch.name/2020/02/16/installing-cgit-nginx-on-debian[https://blog.stefan-koch.name/2020/02/16/installing-cgit-nginx-on-debian]
* https://golang.org/cmd/go/#hdr-Remote_import_paths[https://golang.org/cmd/go/#hdr-Remote_import_paths]
* https://mygit.katolaz.net/katolaz/cgit-70/commit/b522a302c9c4fb9fd9e1ea829ee990afc74980ca[https://mygit.katolaz.net/katolaz/cgit-70/commit/b522a302c9c4fb9fd9e1ea829ee990afc74980ca]
